version: 2
updates:
  # Maintain dependencies for pnpm
  - package-ecosystem: "npm"
    directory: "/webapp"
    schedule:
      interval: "weekly"
  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"