spring:
  application:
    name: one-percent-better
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/one-percent-better
    username: user
    password: password
github:
  token: ""
  username: ""
app:
  check-in:
    schedule-cron: "0 0 */1 * * *"
    bootstrap:
      enabled: true
date: 2025-05-01
    projects:
      - "shazxrin/one-percent-better"
- "shazxrin/notifier"
      - "shazxrin/backbone"
