spring:
  application:
    name: one-percent-better
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/one-percent-better
    username: user
    password: password
github:
  token: ""
  username: ""
app:
  check-in:
    schedule-cron: "0 0 */1 * * *"
    bootstrap-date: 2025-05-01
    bootstrap-projects:
      - "shazxrin/app-one-percent-better"
      - "shazxrin/infra-backbone"
