spring:
  application:
    name: one-percent-better
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/one-percent-better
    username: user
    password: password
github:
  token: ""
  username: ""
app:
  check-in-cron: "0 0 */1 * * *"
