spring:
  application:
    name: one-percent-better
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/one-percent-better
    username: user
    password: password
  rabbitmq:
    host: localhost
    username: user
    password: password
  ai:
    openai:
      api-key: ""
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash-lite
github:
  token: ""
  username: ""
app:
  check-in:
    schedule-cron: "0 0 */1 * * *"
    bootstrap:
      enabled: true
      date: 2025-05-01
      projects:
        - "shazxrin/one-percent-better"
  reminder:
    schedule-cron: "0 0 */1 * * *"
