CREATE TABLE check_in_habits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date                                    NOT NULL,
    amount     INTEGER                                 NOT NULL,
    notes      VARCHAR(100),
    habit_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_habits PRIMARY KEY (id)
);

ALTER TABLE check_in_habits
    ADD CONSTRAINT FK_CHECK_IN_HABITS_ON_HABIT FOREIGN KEY (habit_id) REFERENCES habits (id);
