spring:
  application:
    name: one-percent-better
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/one-percent-better
    username: user
    password: password
  rabbitmq:
    host: localhost
    username: user
    password: password
  ai:
    openai:
      api-key: "api-key"
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash-lite
  liquibase:
    change-log: db/changelog-master.yaml
server:
  error:
    whitelabel:
      enabled: false
github:
  username: "username"
  token: "token"
app:
  check-in:
    project:
      schedule-cron: "0 0 */1 * * *"
  coach:
    reminder:
      schedule-cron: "0 0 */1 * * *"
management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    logging:
      export:
        enabled: true
      endpoint: http://localhost:4318/v1/logs
    tracing:
      export:
        enabled: true
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
        step: 10s
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true
