spring:
  ai:
    openai:
      api-key: "api-key"
github:
  username: "username"
  token: "token"
app:
  check-in:
    project:
      schedule-cron: "0 0 */1 * * *"
  coach:
    reminder:
      schedule-cron: "0 0 */1 * * *"
management:
  otlp:
    logging:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
    metrics:
      export:
        enabled: false
  tracing:
    enabled: false
  observations:
    annotations:
      enabled: false