spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  liquibase:
    enabled: false
  rabbitmq:
    listener:
      direct:
        auto-startup: false
      simple:
        auto-startup: false
  docker:
    compose:
      enabled: false
management:
  otlp:
    logging:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
    metrics:
      export:
        enabled: false
  tracing:
    enabled: false
  observations:
    annotations:
      enabled: false