-- liquibase formatted sql

-- changeset rin:1748759963403-1
CREATE TABLE check_ins
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date                                    NOT NULL,
    count      INTEGER                                 NOT NULL,
    streak     INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_ins PRIMARY KEY (id)
);

-- changeset rin:1748759963403-2
CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner      VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

