name: "otlp-one-percent-better"
services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otlp/alloy:/etc/alloy
    command:
      - 'run'
      - '/etc/alloy/config.alloy'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./otlp/grafana:/etc/grafana/provisioning

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9090:8080"
    volumes:
      - ./otlp/mimir/mimir.yaml:/etc/mimir/mimir.yaml
      - mimir-data:/data
    command:
      - '-config.file=/etc/mimir/mimir.yaml'
      - '-target=all'

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: root
    ports:
      - "3200:3200"
    volumes:
      - ./otlp/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo-data:/tmp/tempo
    command:
      - '--config.file=/etc/tempo/tempo.yaml'

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./otlp/loki/loki-config.yaml:/etc/loki/loki.yaml
      - loki-data:/loki
    command:
      - '--config.file=/etc/loki/loki.yaml'

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - minio-data:/data
    command: server /data --address ":9000" --console-address ":9001"
  minio-init:
    image: minio/mc
    container_name: minio-client
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 user password 2>/dev/null) do echo '...' && sleep 1; done;
      mc rm -r --force myminio/loki;
      mc mb myminio/loki;
      mc anonymous set public myminio/loki;
      mc rm -r --force myminio/mimir-blocks;
      mc mb myminio/mimir-blocks;
      mc anonymous set public myminio/mimir-blocks;
      mc rm -r --force myminio/mimir-ruler;
      mc mb myminio/mimir-ruler;
      mc anonymous set public myminio/mimir-ruler;
      mc rm -r --force myminio/mimir-alertmanager;
      mc mb myminio/mimir-alertmanager;
      mc anonymous set public myminio/mimir-alertmanager;
      mc rm -r --force myminio/tempo;
      mc mb myminio/tempo;
      mc anonymous set public myminio/tempo;
      exit 0
      "
    depends_on:
      - minio

volumes:
  grafana-storage: {}
  mimir-data: {}
  tempo-data: {}
  loki-data: {}
  minio-data: {}
