name: "otlp-one-percent-better"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=14d'
      - '--web.enable-remote-write-receiver'

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./alloy:/etc/alloy
    command:
      - 'run'
      - '/etc/alloy/config.alloy'
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: root
    ports:
      - "3200:3200"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo-data:/tmp/tempo
    command:
      - '--config.file=/etc/tempo/tempo.yaml'
    depends_on:
      - prometheus

volumes:
  grafana-storage: {}
  prometheus-data: {}
  tempo-data: {}
