name: Publish (Web)
inputs:
  gpr-username:
    description: "GitHub Package Registry username for authentication"
    required: true
  gpr-token-container:
    description: "GitHub Package Registry token to authenticate with container registry"
    required: true
  image-name:
    description: "Image name to be used"
    required: true
  image-tag:
    description: "Image tag to be used"
    required: true
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Authenticate Container Registry
      shell: bash
      run: echo "${{ inputs.gpr-token-container }}" | docker login ghcr.io -u ${{ inputs.gpr-username }} --password-stdin

    - name: Build Container Image
      shell: bash
      working-directory: web
      run: docker build . -t ghcr.io/shazxrin/one-percent-better:${{ inputs.image-tag }}

    - name: Push Container Image
      shell: bash
      run: docker push ghcr.io/shazxrin/one-percent-better:${{ inputs.image-tag }}
