CREATE TABLE check_in_habits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date                                    NOT NULL,
    amount     INTEGER                                 NOT NULL,
    notes      VARCHAR(1000),
    habit_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_habits PRIMARY KEY (id)
);

CREATE TABLE check_in_projects
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date          date                                    NOT NULL,
    hash          VARCHAR(255),
    type          VARCHAR(255),
    message       VARCHAR(1000),
    project_id    BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_projects PRIMARY KEY (id)
);

CREATE TABLE habits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_habits PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

ALTER TABLE check_in_habits
    ADD CONSTRAINT FK_CHECK_IN_HABITS_ON_HABIT FOREIGN KEY (habit_id) REFERENCES habits (id);

ALTER TABLE check_in_projects
    ADD CONSTRAINT FK_CHECK_IN_PROJECTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

