-- liquibase formatted sql

-- changeset rin:1753618887686-1
CREATE TABLE check_in_habits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date                                    NOT NULL,
    amount     INTEGER                                 NOT NULL,
    notes      VARCHAR(1000),
    habit_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_habits PRIMARY KEY (id)
);

-- changeset rin:1753618887686-2
CREATE TABLE check_in_project_aggregate_daily_summaries
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            date                                    NOT NULL,
    no_of_check_ins INTEGER                                 NOT NULL,
    streak          INTEGER                                 NOT NULL,
    created_at      date,
    updated_at      date,
    CONSTRAINT pk_check_in_project_aggregate_daily_summaries PRIMARY KEY (id)
);

-- changeset rin:1753618887686-3
CREATE TABLE check_in_project_daily_summaries
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            date                                    NOT NULL,
    no_of_check_ins INTEGER                                 NOT NULL,
    streak          INTEGER                                 NOT NULL,
    project_id      BIGINT                                  NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_project_daily_summaries PRIMARY KEY (id)
);

-- changeset rin:1753618887686-4
CREATE TABLE check_in_projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date                                    NOT NULL,
    hash       VARCHAR(255),
    type       VARCHAR(255),
    message    VARCHAR(1000),
    project_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_projects PRIMARY KEY (id)
);

-- changeset rin:1753618887686-5
CREATE TABLE habits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_habits PRIMARY KEY (id)
);

-- changeset rin:1753618887686-6
CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

-- changeset rin:1753618887686-7
ALTER TABLE check_in_habits
    ADD CONSTRAINT FK_CHECK_IN_HABITS_ON_HABIT FOREIGN KEY (habit_id) REFERENCES habits (id);

-- changeset rin:1753618887686-8
ALTER TABLE check_in_projects
    ADD CONSTRAINT FK_CHECK_IN_PROJECTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

-- changeset rin:1753618887686-9
ALTER TABLE check_in_project_daily_summaries
    ADD CONSTRAINT FK_CHECK_IN_PROJECT_DAILY_SUMMARIES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

