-- liquibase formatted sql

-- changeset rin:create-habits
CREATE TABLE habits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_habits PRIMARY KEY (id)
);

-- changeset rin:projects
CREATE TABLE projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

-- changeset rin:create-check-in-habits
CREATE TABLE check_in_habits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date                                    NOT NULL,
    amount     INTEGER                                 NOT NULL,
    notes      VARCHAR(1000),
    habit_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_habits PRIMARY KEY (id)
);
-- changeset rin:create-check-in-habits-fk
ALTER TABLE check_in_habits
    ADD CONSTRAINT FK_CHECK_IN_HABITS_ON_HABIT FOREIGN KEY (habit_id) REFERENCES habits (id);

-- changeset rin:create-check-in-projects
CREATE TABLE check_in_projects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    hash       VARCHAR(255),
    type       VARCHAR(255),
    message    VARCHAR(1000),
    project_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_projects PRIMARY KEY (id)
);
-- changeset rin:create-check-in-projects-fk
ALTER TABLE check_in_projects
    ADD CONSTRAINT fk_check_in_projects_on_project FOREIGN KEY (project_id) REFERENCES projects (id);

-- changeset rin:create-check-in-project-aggregate-daily-summaries
CREATE TABLE check_in_project_aggregate_daily_summaries
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date                    date                                    NOT NULL,
    no_of_check_ins         INTEGER                                 NOT NULL,
    streak                  INTEGER                                 NOT NULL,
    type_distribution       JSONB                                   NOT NULL,
    hour_distribution       JSONB                                   NOT NULL,
    project_distribution    JSONB                                   NOT NULL,
    created_at              date,
    updated_at              date,
    CONSTRAINT pk_check_in_project_aggregate_daily_summaries PRIMARY KEY (id)
);
-- changeset rin:create-check-in-project-aggregate-daily-summaries-uc
ALTER TABLE check_in_project_aggregate_daily_summaries
    ADD CONSTRAINT uc_check_in_project_aggregate_daily_summaries_date UNIQUE (date);
-- changeset rin:create-check-in-project-aggregate-daily-summaries-seed
INSERT INTO check_in_project_aggregate_daily_summaries (date, no_of_check_ins, streak, type_distribution, hour_distribution, project_distribution, created_at, updated_at)
WITH
    dates AS (
        SELECT generate_series(
           '2025-01-01'::date,
           '2025-12-31'::date,
           '1 day'::interval
        )::date AS date
    )
SELECT
    date,
    0 AS no_of_check_ins,
    0 AS streak,
    '{}'::jsonb AS type_distribution,
    '{ "0": 0, "1": 0, "2": 0, "3": 0, "4": 0, "5": 0, "6": 0, "7": 0, "8": 0, "9": 0, "10": 0, "11": 0, "12": 0, "13": 0, "14": 0, "15": 0, "16": 0, "17": 0, "18": 0, "19": 0, "20": 0,"21": 0, "22": 0, "23": 0 }'::jsonb AS hour_distribution,
    '{}'::jsonb AS project_distribution,
    CURRENT_TIMESTAMP AS created_at,
    CURRENT_TIMESTAMP AS updated_at
FROM dates
ON CONFLICT (date) DO NOTHING;

-- changeset rin:create-check-in-project-daily-summaries
CREATE TABLE check_in_project_daily_summaries
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date                date                                    NOT NULL,
    no_of_check_ins     INTEGER                                 NOT NULL,
    streak              INTEGER                                 NOT NULL,
    type_distribution   JSONB                                   NOT NULL,
    hour_distribution   JSONB                                   NOT NULL,
    project_id          BIGINT                                  NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_project_daily_summaries PRIMARY KEY (id)
);
-- changeset rin:create-check-in-project-daily-summaries-fk
ALTER TABLE check_in_project_daily_summaries
    ADD CONSTRAINT fk_check_in_project_daily_summaries_on_project FOREIGN KEY (project_id) REFERENCES projects (id);
-- changeset rin:create-check-in-project-daily-summaries-uc
ALTER TABLE check_in_project_daily_summaries
    ADD CONSTRAINT uc_check_in_project_daily_summaries_date_project UNIQUE (date, project_id);

-- changeset rin:create-check-in-project-aggregate-weekly-summaries
CREATE TABLE check_in_project_aggregate_weekly_summaries
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year                    INTEGER                                 NOT NULL,
    week_no                 INTEGER                                 NOT NULL,
    start_date              date                                    NOT NULL,
    end_date                date                                    NOT NULL,
    no_of_check_ins         INTEGER                                 NOT NULL,
    streak                  INTEGER                                 NOT NULL,
    type_distribution       JSONB                                   NOT NULL,
    hour_distribution       JSONB                                   NOT NULL,
    project_distribution    JSONB                                   NOT NULL,
    day_distribution        JSONB                                   NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_project_aggregate_weekly_summaries PRIMARY KEY (id)
);
-- changeset rin:create-check-in-project-aggregate-weekly-summaries-uc
ALTER TABLE check_in_project_aggregate_weekly_summaries
    ADD CONSTRAINT uc_check_in_project_aggregate_weekly_summaries_year_week UNIQUE (year, week_no);
-- changeset rin:create-check-in-project-aggregate-weekly-summaries-seed
INSERT INTO check_in_project_aggregate_weekly_summaries (
    year,
    week_no,
    start_date,
    end_date,
    no_of_check_ins,
    streak,
    type_distribution,
    hour_distribution,
    project_distribution,
    day_distribution,
    created_at,
    updated_at
)
WITH
    weekly_dates AS (
        SELECT DISTINCT
            EXTRACT(ISOYEAR FROM generate_series)::int AS year,
            EXTRACT(WEEK FROM generate_series)::int AS week_no,
            (date_trunc('week', generate_series))::date AS start_date,
            (date_trunc('week', generate_series) + interval '6 days')::date AS end_date
        FROM generate_series(
            '2025-01-01'::date,
            '2025-12-31'::date,
            '1 day'::interval
        )
    )
SELECT
    wd.year,
    wd.week_no,
    wd.start_date,
    wd.end_date,
    0 AS no_of_check_ins,
    0 AS streak,
    '{}'::jsonb AS type_distribution,
    '{ "0": 0, "1": 0, "2": 0, "3": 0, "4": 0, "5": 0, "6": 0, "7": 0, "8": 0, "9": 0, "10": 0, "11": 0, "12": 0, "13": 0, "14": 0, "15": 0, "16": 0, "17": 0, "18": 0, "19": 0, "20": 0,"21": 0, "22": 0, "23": 0 }'::jsonb AS hour_distribution,
    '{}'::jsonb AS project_distribution,
    '{ "MONDAY": 0, "TUESDAY": 0, "WEDNESDAY": 0, "THURSDAY": 0, "FRIDAY": 0, "SATURDAY": 0, "SUNDAY": 0 }'::jsonb AS day_distribution,
    CURRENT_TIMESTAMP AS created_at,
    CURRENT_TIMESTAMP AS updated_at
FROM weekly_dates wd
ON CONFLICT DO NOTHING;

-- changeset rin:create-check-in-project-weekly-summaries
CREATE TABLE check_in_project_weekly_summaries
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year                INTEGER                                 NOT NULL,
    week_no             INTEGER                                 NOT NULL,
    start_date          date                                    NOT NULL,
    end_date            date                                    NOT NULL,
    no_of_check_ins     INTEGER                                 NOT NULL,
    streak              INTEGER                                 NOT NULL,
    type_distribution   JSONB                                   NOT NULL,
    hour_distribution   JSONB                                   NOT NULL,
    day_distribution    JSONB                                   NOT NULL,
    project_id          BIGINT                                  NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_project_weekly_summaries PRIMARY KEY (id)
);
-- changeset rin:create-check-in-project-weekly-summaries-fk
ALTER TABLE check_in_project_weekly_summaries
    ADD CONSTRAINT fk_check_in_project_weekly_summaries_on_project FOREIGN KEY (project_id) REFERENCES projects (id);
-- changeset rin:create-check-in-project-weekly-summaries-uc
ALTER TABLE check_in_project_weekly_summaries
    ADD CONSTRAINT uc_check_in_project_weekly_summaries_date_project UNIQUE (year, week_no, project_id);

-- changeset rin:create-check-in-project-aggregate-monthly-summaries
CREATE TABLE check_in_project_aggregate_monthly_summaries
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year                    INTEGER                                 NOT NULL,
    month_no                INTEGER                                 NOT NULL,
    start_date              date                                    NOT NULL,
    end_date                date                                    NOT NULL,
    no_of_check_ins         INTEGER                                 NOT NULL,
    streak                  INTEGER                                 NOT NULL,
    type_distribution       JSONB                                   NOT NULL,
    hour_distribution       JSONB                                   NOT NULL,
    project_distribution    JSONB                                   NOT NULL,
    date_distribution       JSONB                                   NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_project_aggregate_monthly_summaries PRIMARY KEY (id)
);
-- changeset rin:create-check-in-project-aggregate-monthly-summaries-uc
ALTER TABLE check_in_project_aggregate_monthly_summaries
    ADD CONSTRAINT uc_check_in_project_aggregate_monthly_summaries_year_month UNIQUE (year, month_no);
-- changeset rin:create-check-in-project-aggregate-monthly-summaries-seed
INSERT INTO check_in_project_aggregate_monthly_summaries (
    year,
    month_no,
    start_date,
    end_date,
    no_of_check_ins,
    streak,
    type_distribution,
    hour_distribution,
    project_distribution,
    date_distribution,
    created_at,
    updated_at
)
WITH
    monthly_dates AS (
        SELECT DISTINCT
            EXTRACT(YEAR FROM generate_series)::int AS year,
            EXTRACT(MONTH FROM generate_series)::int AS month_no,
            date_trunc('month', generate_series)::date AS start_date,
            (date_trunc('month', generate_series) + interval '1 month - 1 day')::date AS end_date
        FROM generate_series(
            '2025-01-01'::date,
            '2025-12-31'::date,
            '1 day'::interval
        )
    )
SELECT
    md.year,
    md.month_no,
    md.start_date,
    md.end_date,
    0 AS no_of_check_ins,
    0 AS streak,
    '{}'::jsonb AS type_distribution,
    '{ "0": 0, "1": 0, "2": 0, "3": 0, "4": 0, "5": 0, "6": 0, "7": 0, "8": 0, "9": 0, "10": 0, "11": 0, "12": 0, "13": 0, "14": 0, "15": 0, "16": 0, "17": 0, "18": 0, "19": 0, "20": 0,"21": 0, "22": 0, "23": 0 }'::jsonb AS hour_distribution,
    '{}'::jsonb AS project_distribution,
    '{ "1": 0, "2": 0, "3": 0, "4": 0, "5": 0, "6": 0, "7": 0, "8": 0, "9": 0, "10": 0, "11": 0, "12": 0, "13": 0, "14": 0, "15": 0, "16": 0, "17": 0, "18": 0, "19": 0, "20": 0, "21": 0, "22": 0, "23": 0, "24": 0, "25": 0, "26": 0, "27": 0, "28": 0, "29": 0, "30": 0, "31": 0 }'::jsonb AS date_distribution,
    CURRENT_TIMESTAMP AS created_at,
    CURRENT_TIMESTAMP AS updated_at
FROM monthly_dates md
ON CONFLICT (year, month_no) DO NOTHING;

-- changeset rin:create-check-in-project-monthly-summaries
CREATE TABLE check_in_project_monthly_summaries
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year                INTEGER                                 NOT NULL,
    month_no            INTEGER                                 NOT NULL,
    start_date          date                                    NOT NULL,
    end_date            date                                    NOT NULL,
    no_of_check_ins     INTEGER                                 NOT NULL,
    streak              INTEGER                                 NOT NULL,
    type_distribution   JSONB                                   NOT NULL,
    hour_distribution   JSONB                                   NOT NULL,
    date_distribution   JSONB                                   NOT NULL,
    project_id          BIGINT                                  NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_check_in_project_monthly_summaries PRIMARY KEY (id)
);
-- changeset rin:create-check-in-project-monthly-summaries-fk
ALTER TABLE check_in_project_monthly_summaries
    ADD CONSTRAINT fk_check_in_project_monthly_summaries_on_project FOREIGN KEY (project_id) REFERENCES projects (id);
-- changeset rin:create-check-in-project-monthly-summaries-uc
ALTER TABLE check_in_project_monthly_summaries
    ADD CONSTRAINT uc_check_in_project_monthly_summaries_project_id_year_month UNIQUE (project_id, year, month_no);
