apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:8080/prometheus
    isDefault: true
  
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: 'Mimir'
      tracesToLogs:
        datasourceUid: 'Loki'
  
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
