name: Push Tag
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test
  
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Publish
        uses: ./.github/actions/publish
        with:
          version_name: ${{ github.ref_name }}
