name: Push to Main Branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Build (App)
        uses: ./.github/actions/build-gradle
        with:
          module-name: app
          gpr-username: ${{ github.actor }}
          gpr-token-maven: ${{ secrets.GPR_TOKEN }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Test (App)
        uses: ./.github/actions/test-gradle
        with:
          module-name: app
          gpr-username: ${{ github.actor }}
          gpr-token-maven: ${{ secrets.GPR_TOKEN }}
